import { jsx as _jsx } from "react/jsx-runtime";
import React from 'react';
const Table = React.forwardRef(({ className = '', ...props }, ref) => (_jsx("div", { className: "relative w-full overflow-auto", children: _jsx("table", { ref: ref, className: `w-full caption-bottom text-sm ${className}`, ...props }) })));
Table.displayName = 'Table';
const TableHeader = React.forwardRef(({ className = '', ...props }, ref) => (_jsx("thead", { ref: ref, className: `[&_tr]:border-b ${className}`, ...props })));
TableHeader.displayName = 'TableHeader';
const TableBody = React.forwardRef(({ className = '', ...props }, ref) => (_jsx("tbody", { ref: ref, className: `[&_tr:last-child]:border-0 ${className}`, ...props })));
TableBody.displayName = 'TableBody';
const TableRow = React.forwardRef(({ className = '', ...props }, ref) => (_jsx("tr", { ref: ref, className: `border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted ${className}`, ...props })));
TableRow.displayName = 'TableRow';
const TableHead = React.forwardRef(({ className = '', ...props }, ref) => (_jsx("th", { ref: ref, className: `h-12 px-4 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0 ${className}`, ...props })));
TableHead.displayName = 'TableHead';
const TableCell = React.forwardRef(({ className = '', ...props }, ref) => (_jsx("td", { ref: ref, className: `p-4 align-middle [&:has([role=checkbox])]:pr-0 ${className}`, ...props })));
TableCell.displayName = 'TableCell';
export { Table, TableHeader, TableBody, TableRow, TableHead, TableCell };
